services:
  - type: web
    name: voc-fastapi
    env: python
    region: oregon  # You can choose from: ohio, oregon, frankfurt, singapore
    plan: free
    branch: main  # Change if your default branch is different
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    